package(default_visibility = ["//visibility:public"])

java_binary(
    name = "twitch-bot",
    srcs = ["Main.java"],
    deps = [
        "//thirdparty:com_github_twitch4j_twitch4j",
    ],
    main_class = "twitch.Main",
)